language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci
cache:
  npm: true
  directories:
    - ~/.cache
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: fordevs-react
  skip_cleanup: true
notifications:
  email: false
