language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
sript:
  - eslint 'src/**'
  - yarn test:coveralls
  - yarn test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: fordevs-react-wss
  skip_cleanup: true
notifications:
  email: false
